<?php
namespace App\Controller\Amazonie;

use App\Controller\AppController;
use Cake\Event\Event;

/**
 * Datations Controller
 *
 * @property \App\Model\Table\DatationsTable $Datations
 */
class DatationsController extends AppController
{

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow(['index', 'view']);
    }

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['Laboratoires', 'Sites']
        ];
        $datations = $this->paginate($this->Datations);

        $this->set(compact('datations'));
        $this->set('_serialize', ['datations']);
        $this->viewBuilder()->layout('amazonieLayout');
    }

    /**
     * View method
     *
     * @param string|null $id Datation id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $datation = $this->Datations->get($id, [
            'contain' => ['Laboratoires', 'Sites', 'Materiels', 'Objets', 'Publications']
        ]);

        $this->set('datation', $datation);
        $this->set('_serialize', ['datation']);
        $this->viewBuilder()->layout('amazonieLayout');
    }

}
