<?php

namespace App\Controller\Amazonie;

use App\Controller\AppController;
use Cake\Event\Event;

class DefaultController extends AppController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow(['home']);
    }

    public function home()
    {
        $this->viewBuilder()->layout('amazonieLayout');
        $this->viewBuilder()->template('index');
        $this->set('accueil', '');
    }
}
