<?php
namespace App\Controller\Amazonie;

use App\Controller\AppController;
use Cake\Event\Event;
/**
 * Publications Controller
 *
 * @property \App\Model\Table\PublicationsTable $Publications
 */
class PublicationsController extends AppController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow(['index', 'view']);
    }

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $publications = $this->paginate($this->Publications);

        $this->set(compact('publications'));
        $this->set('_serialize', ['publications']);
        $this->viewBuilder()->layout('amazonieLayout');
    }

    /**
     * View method
     *
     * @param string|null $id Publication id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $publication = $this->Publications->get($id, [
            'contain' => ['Auteurs', 'Datations']
        ]);

        $this->set('publication', $publication);
        $this->set('_serialize', ['publication']);
        $this->viewBuilder()->layout('amazonieLayout');
    }

}
