<?php
namespace App\Controller\Afrique;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\Routing\Router;
use Cake\View\View;

/**
 * Datations Controller
 *
 * @property \App\Model\Table\DatationsTable $Datations
 */
class DatationsController extends AppController
{

    public $helpers = array('GoogleMap');


    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow();
    }






    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        //Building the request
        $query = $this->Datations->find()->where(['Datations.source_id' => 1]);
        //Request is coming from ajax call
        if($this->request->is('ajax')){
            //set the pagination informations
            $this->paginate = [
                'contain' => ['Laboratoires', 'Sites'],
                'page' => $this->request->query('page'),
                'limit' => $this->request->query('limit'),
                'order' => [
                    'Datations.date_bp' => 'asc'
                ]
            ];

            //Check if there is or not search parameters.
            if(count($this->request->data(['params']) != 0)){
                $params = $this->request->data(['params']);
                $conditions = $this->Search->searchConditions($params, 'Datations');
                $datas = $this->paginate($query->andWhere($conditions));
            }else{
                $datas = $this->paginate($query);
            }

            //Get pagination for the view.
            $view = new View($this->request, $this->response, null);
            $view->layout = 'emptyLayout';
            $view->viewPath = '../Template/All';
            $pagination = $view->render('pagination');


            //Change the render layout to render an ajax object
            $this->RequestHandler->renderAs($this, 'json');
            $this->response->type('application/json');
            $this->viewBuilder()->layout('ajax');

            $this->set(compact('datas'));
            $this->set(compact('pagination'));
            $this->set('_serialize', ['datas', 'pagination']);
        }else{
            $this->set('searchUrl', Router::url(['controller' => 'Datations', 'prefix' => 'afrique', '?' => ['page' => 1],]));

            $this->paginate = [
                'contain' => ['Laboratoires', 'Sites'],
                'limit' => 10,
                'page' => 1,
                'order' => [
                    'Datations.date_bp' => 'asc'
                ]
            ];
            $datations = $this->paginate($query);
            $this->set(compact('datations'));
            $this->set('activedatation', true);
            $this->set('_serialize', ['datations']);
            $this->viewBuilder()->layout('afriqueCentraleLayout');
        }
    }






    /**
     * View method
     *
     * @param string|null $id Datation id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $datation = $this->Datations->get($id, [
            'contain' => ['Laboratoires', 'Sites', 'Materiels', 'Objets', 'Publications']
        ]);

        $this->set('datation', $datation);
        $this->set('_serialize', ['datation']);
        $this->set('activedatation', true);
        $this->viewBuilder()->layout('afriqueCentraleLayout');
    }





    /**
     * @param \Cake\Network\Request\null
     * @return \Cake\Network\Response|null
     */
    public  function cartographie() {
        $query = $this->Datations->find()->where(['Datations.source_id' => 1]);
        $max = $query->select(['date_bp'])->max('date_bp')->toArray();
        $min = $query->select(['date_bp'])->min('date_bp')->toArray();

        if ($this->request->is('get')){
            $val =  ($max['date_bp'] + $min['date_bp']) / 2;

            $datations = $query->select(['id', 'date_bp', 'erreur_standard', 'date_calibree'])
                                ->contain(['Sites' => function($q){ return $q->select(['id', 'name', 'latitude', 'longitude']);}])
                                ->andWhere(function($exp, $q) use ($val){
                                    $bornsup = $q->newExpr()->add('Datations.date_bp + Datations.erreur_standard');
                                    $borninf = $q->newExpr()->add('Datations.date_bp - Datations.erreur_standard');
                                    return $exp
                                        ->between($val, $borninf, $bornsup);
                                });

            $this->set('cartographie', true);
            $this->set('minimum', -1 * $max['date_bp']);
            $this->set('maximum', -1 * $min['date_bp']);
            $this->set(compact('datations'));
            $this->viewBuilder()->layout('afriqueCentraleLayout');

        }else{
            $this->RequestHandler->renderAs($this, 'json');
            $this->response->type('application/json');
            $this->viewBuilder()->layout('ajax');

            $params = $this->request->data(['params']);
            $val = $params['valeur'];
            $cumul = $params['statutCumul'];
            $maxVal = $params['minCumul'];
            $minVal = $params['maxCumul'];

            //Le cas ou on a une valeur issue de l'animation du curseur
            if ($val < 0){
                $val = $val * -1;
            }

            //Condition de recherche differente en fonction du choix de cumuler les valeurs ou pas
            if ($cumul === "non") {
                $datations = $query->select(['id', 'date_bp', 'erreur_standard', 'date_calibree'])
                    ->contain   (['Sites' => function($q){ return $q->select(['id', 'name', 'latitude', 'longitude']);}])
                    ->andWhere(function($exp, $q) use ($val){
                        $bornsup = $q->newExpr()->add('Datations.date_bp + Datations.erreur_standard');
                        $borninf = $q->newExpr()->add('Datations.date_bp - Datations.erreur_standard');
                        return $exp
                            ->between($val, $borninf, $bornsup);
                    });
            } else {
                if($maxVal < 0 ) {
                    $maxVal = $maxVal * (-1);
                }
                if($minVal < 0 ) {
                    $minVal = $minVal * (-1);
                }

                $datations = $query->select(['id', 'date_bp', 'erreur_standard', 'date_calibree'])
                    ->contain   (['Sites' => function($q){ return $q->select(['id', 'name', 'latitude', 'longitude']);}])
                    ->andWhere(function($exp, $q) use ($maxVal, $minVal){
                        $bornsup = $q->newExpr()->add('Datations.date_bp + Datations.erreur_standard');
                        $borninf = $q->newExpr()->add('Datations.date_bp - Datations.erreur_standard');
                        return $exp
                            ->lte($borninf, $maxVal)
                            ->gte($bornsup, $minVal);
                    });
            }

            $index = 0;
            $datas = [];
            foreach ($datations as $data){
                $datas[$index++] = $data;
            }

            $this->set(compact('datas'));

        }
    }




    /**
     *Permet de récupérer les premières datations issues de l'affichage de la carte.
     *
     * @param null
     * @return datations
     */
    public function getSessionDatations(){
        $this->RequestHandler->renderAs($this, 'json');
        $this->response->type('application/json');
        $this->viewBuilder()->layout('ajax');

        if($this->request->is('ajax')) {
            $datas = $this->request->session()->read('mapdatations');

            $this->set(compact('datas'));
            $this->set('_serialize', ['datas']);
        }
    }

}
