<?php

namespace App\Controller\Afrique;

use App\Controller\AppController;
use Cake\Event\Event;

class DefaultController extends AppController
{
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow(['home']);
    }

    public function home()
    {
        $this->set('accueil', "list-group-item active");
        $this->viewBuilder()->layout('afriqueCentraleLayout');
        $this->viewBuilder()->template('index');
    }
}
